version: "3"
services:
  scraping:
    build: .
    container_name: scraping
    shm_size: "2gb"
    volumes:
      - .:/app
    environment:
      - DISPLAY=:99
    stdin_open: true
    tty: true
    entrypoint: ["python", "-m", "script.scraping"]

  tests:
    build: .
    container_name: scraping_tests
    profiles:
      - test
    entrypoint: ["pytest", "-v", "tests/"]
